"""Audit temporal states on real recordings and known synthetic transformations."""
from collections import Counter
import argparse
import hashlib
import json
from pathlib import Path
import sys

from app.pipeline import trace_line
from app.recording import read_frames
from app.replay import replay
from app.replay.social import recording_session
from app.social_pipeline import SocialPipeline
from app.social_scenarios import controlled_scenarios
from app.state.social_models import SocialState, TemporalConfig
from app.state.tracks import TrackConfig


def audit_frames(frames, session, config=None, track_config=None, output=None):
    config = config or TemporalConfig()
    tracks = track_config or TrackConfig()
    hashes = {}
    gaze, trends, zones, flags = Counter(), Counter(), Counter(), Counter()
    missing_count = changes = observed = 0
    for speed in (0, 1, 2):
        pipeline = SocialPipeline(session, tracks, config)
        clock = [0.0]
        digest = hashlib.sha256()
        def emit(frame):
            nonlocal missing_count, changes, observed
            result = pipeline.process(frame)
            state = result["social_state"]
            SocialState.model_validate(state)
            if state["robot_timestamp_us"] != frame["timestamp"]:
                raise ValueError("source timestamp changed")
            live_uids = {p["uid"] for p in frame["people"]}
            if {p["uid"] for p in state["people"] if p["visibility"] == "OBSERVED"} != live_uids:
                raise ValueError("observed person set changed")
            for person in state["people"]:
                evidence = person["evidence"]
                if person["gaze_state"] != "UNKNOWN" and not evidence["gaze_valid"]:
                    raise ValueError("gaze label without valid evidence")
                if person["relative_distance_trend"] != "UNKNOWN" and not evidence["distance_trend_valid"]:
                    raise ValueError("distance trend without valid evidence")
                if not 0 <= evidence["gaze_valid_coverage_s"] <= config.window_s + 1e-9:
                    raise ValueError("gaze coverage exceeds window")
                fraction = evidence["gaze_fraction"]
                if fraction is not None and not 0 <= fraction <= 1 + 1e-9:
                    raise ValueError("invalid gaze fraction")
                if person["visibility"] != "OBSERVED":
                    if any(person[k] != "UNKNOWN" for k in ("gaze_state", "distance_zone", "relative_distance_trend")):
                        raise ValueError("missing person has current categorical cues")
                if speed == 0:
                    if person["visibility"] == "OBSERVED":
                        observed += 1
                        gaze[person["gaze_state"]] += 1
                        trends[person["relative_distance_trend"]] += 1
                        zones[person["distance_zone"]] += 1
                        flags.update(person["validity_flags"])
                    else:
                        missing_count += 1
            line = trace_line(state)
            digest.update(line.encode())
            if speed == 0:
                changes += len(state["cue_changes"])
                if output is not None:
                    output.write(line)
        replay(frames, emit, speed=speed, monotonic=lambda: clock[0],
               sleep=lambda delay: clock.__setitem__(0, clock[0] + delay))
        hashes[str(speed)] = digest.hexdigest()
    if len(set(hashes.values())) != 1:
        raise ValueError("social traces differ by replay speed")
    return {"frames": len(frames), "observed_person_states": observed,
            "missing_person_states": missing_count, "observed_gaze_states": dict(sorted(gaze.items())),
            "observed_relative_trends": dict(sorted(trends.items())), "observed_distance_zones": dict(sorted(zones.items())),
            "validity_flags": dict(sorted(flags.items())), "cue_changes": changes,
            "trace_sha256_by_speed": hashes, "checks_passed": True}


def report_markdown(report):
    lines = ["# Temporal SocialState validation", "",
             "Generated by `python -m app.validate_social`. These checks validate software behavior;",
             "the unannotated real recordings do not establish engagement accuracy. Counts below include observed UIDs only.",
             "", f"Configuration: `{report['config_version']}`; calibration status: **PROVISIONAL**.",
             "Distance trends describe robot-relative separation, regardless of which participant is moving.",
             "", "| Recording | Frames | Person observations | Unknown gaze | None | Intermittent | Sustained | Valid distance trend |",
             "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for r in report["recordings"]:
        g = r["observed_gaze_states"]
        valid = r["observed_person_states"] - r["observed_relative_trends"].get("UNKNOWN", 0)
        lines.append(f"| {r['file']} | {r['frames']} | {r['observed_person_states']} | {g.get('UNKNOWN',0)} | "
                     f"{g.get('NONE',0)} | {g.get('INTERMITTENT',0)} | {g.get('SUSTAINED',0)} | {valid} |")
    lines += ["", "## Controlled transformations", "",
              "A copy of a source frame is transformed into 160 synthetic frames. UID, time, gaze, distance,",
              "and robot velocity are explicitly set; stale optional head geometry is removed. These are designed stimuli,",
              "not additional observations of the real participants. Synthetic robot velocities are zero throughout.",
              "", "| Time | Expected gaze | Expected distance trend | Result |",
              "| --- | --- | --- | --- |"]
    for r in report["controlled_checkpoints"]:
        e = r["expected"]
        lines.append(f"| {r['time_s']:.1f} s | {e['gaze_state']} | {e['relative_distance_trend']} | PASS |")
    lines += ["", "Every original recording and the synthetic sequence passed schema/validity checks and identical",
              "full-trace hashes at replay speeds 0/1/2 using a virtual clock. Source SHA-256 hashes were unchanged.",
              "The complete config, per-file label distributions/reasons, implementation hashes, and trace hashes are in `summary.json`.",
              "", "High gaze scores in no-gaze and eye-motion recordings can still produce SUSTAINED under these",
              "provisional thresholds. UID changes restart evidence. Neither issue is hidden by forcing filename labels.", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("recordings", nargs="+")
    parser.add_argument("--config")
    parser.add_argument("--tracking-config")
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args(argv)
    try:
        config = TemporalConfig.from_file(args.config) if args.config else TemporalConfig()
        tracks = TrackConfig.from_file(args.tracking_config) if args.tracking_config else TrackConfig()
        paths = [Path(p) for p in args.recordings]
        if len({p.stem for p in paths}) != len(paths):
            raise ValueError("recording basenames must be unique")
        inputs = [(p, list(read_frames(p)), hashlib.sha256(p.read_bytes()).hexdigest()) for p in paths]
        destination = Path(args.output_dir)
        destination.mkdir(parents=True, exist_ok=False)
        results = []
        for path, frames, source_hash in inputs:
            with (destination / f"{path.stem}.social.jsonl").open("x") as stream:
                result = audit_frames(frames, recording_session(path), config, tracks, output=stream)
            if hashlib.sha256(path.read_bytes()).hexdigest() != source_hash:
                raise ValueError("source recording changed")
            results.append({"file": path.name, "source_sha256": source_hash, **result})
        frames, expectations = controlled_scenarios(inputs[0][1][0])
        with (destination / "synthetic-patterns.observations.jsonl").open("x") as stream:
            for f in frames:
                stream.write(trace_line(f))
        with (destination / "synthetic-patterns.social.jsonl").open("x") as stream:
            synthetic = audit_frames(frames, "synthetic-patterns", config, tracks, stream)
        pipeline = SocialPipeline("synthetic-checkpoints", tracks, config)
        checks = []
        for index, frame in enumerate(frames):
            state = pipeline.process(frame)["social_state"]
            if index in expectations:
                expected = expectations[index]
                actual = {k: state["people"][0][k] for k in expected}
                if actual != expected:
                    raise ValueError(f"controlled checkpoint {index} mismatch: {actual} != {expected}")
                checks.append({"frame_index": index, "time_s": index/10, "expected": expected, "actual": actual})
        root = Path(__file__).resolve().parents[1]
        names = ["app/state/social_models.py", "app/state/features.py", "app/state/estimator.py",
                 "app/social_pipeline.py", "app/replay/social.py", "app/social_scenarios.py", "app/validate_social.py",
                 "app/state/tracks.py", "app/pipeline.py", "app/recording.py", "app/replay/__init__.py", "app/server.py"]
        report = {"config_version": config.version, "config": config.model_dump(), "tracking_config": tracks.__dict__,
                  "recordings": results, "synthetic": synthetic, "controlled_checkpoints": checks,
                  "synthetic_template_file": inputs[0][0].name, "synthetic_template_sha256": inputs[0][2],
                  "implementation_sha256": {n: hashlib.sha256((root/n).read_bytes()).hexdigest() for n in names}}
        (destination / "summary.json").write_text(json.dumps(report, indent=2) + "\n")
        (destination / "report.md").write_text(report_markdown(report))
        print(f"Validated {sum(r['frames'] for r in results)} recorded frames and 160 synthetic frames. Reports: {destination}")
        return 0
    except (ValueError, OSError, RuntimeError) as error:
        print(f"Temporal validation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
