footprint: [[0.18, 0.15], [0.18, -0.15], [-0.18, -0.15], [-0.18, 0.15]]
footprint_padding: 0.01

obstacle_range: 3.0
raytrace_range: 3.5
inflation_radius: 0.18
transform_tolerance: 0.5

observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
  inf_is_valid: true

map_type: costmap
track_unknown_space: true
always_send_full_costmap: true
