DWAPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.25
  min_vel_trans: 0.03
  trans_stopped_vel: 0.05

  max_vel_theta: 0.8
  min_vel_theta: 0.15
  theta_stopped_vel: 0.2

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  sim_time: 2.0
  vx_samples: 10
  vy_samples: 1
  vth_samples: 20
  controller_frequency: 8.0

  path_distance_bias: 20.0
  goal_distance_bias: 16.0
  occdist_scale: 0.01
  forward_point_distance: 0.20
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.30
  latch_xy_goal_tolerance: false

  publish_traj_pc: true
  publish_cost_grid_pc: true
  prune_plan: true
